# dependencies
if(!require(shiny)) install.packages("shiny")
if(!require(randomForest)) install.packages("randomForest")
if(!require(shinythemes)) install.packages("shinythemes")
if(!require(devtools)) install.packages("devtools")
if(!require(shinyIncubator)) devtools::install_github("shiny-incubator", "rstudio")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(grid)) install.packages("grid")
if(!require(markdown)) install.packages("markdown")
if(!require(xtable)) install.packages("xtable")

library(shiny)
library(shinyIncubator)
library(shinythemes)
library(randomForest)
library(ggplot2)
library(grid)
library(markdown)
library(xtable)